### ISSUE TITLE
spot-instances-request tags breaks on-demand instances

### ISSUE THREAD

**Issue by Giaco9NN** [github-aws-runners/terraform-aws-github-runner#4561]
Hi.
 Today we upgraded the module from version 6.4.3 to 6.5.1. Our groups based only on on-demand instances got stuck right after the upgrade. The scale-up lambda silently fails with this error:
"You cannot specify tags for Spot instances requests if there are no Spot instances requests being created by the request."

Below you can see the whole lambda logs:

[logs.txt](https://github.com/user-attachments/files/19853170/logs.txt)

How can we avoid putting those tags in the launch template when running only on-demand instances?

Thanks!

**Comment by npalm** [comment]
Created a PR, rquires some testing before merging.

**Comment by npalm** [comment]
Fix available in release https://github.com/github-aws-runners/terraform-aws-github-runner/releases/tag/v6.5.4 should be available

**Comment by Giaco9NN** [comment]
Hi @npalm, thanks for the help.
I didn't raise a pull request because I wanted to agree on the strategy before implementing it.

Thank you for the help and the rapid fix!

**Comment by pwo3** [comment]
Hi,

I still have this issue when spot instances are not available and trying to fallback on on-demand
(I'm using this parameter `enable_on_demand_failover_for_errors = ["InsufficientInstanceCapacity"]`)

My logs are :
```
There is no Spot capacity available that matches your request.
Create fleet failed, initatiing fall back to on demand instances.
You cannot specify tags for Spot instances requests if there are no Spot instances requests being created by the request.
```
